spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: default
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
   url: jdbc:mysql://localhost:3306/sofco_graha?useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Jakarta
   username: root
   password:
   driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 9900

